---
title: Tyler Goza's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tyler@tylergoza.com
description: "This is just a personal blog for me. Maybe someone will find something
  \ of interest. \n"
baseurl: ''
url: https://blog.tylergoza.com
github_username: tylerwgoza
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-archives
- jekyll-assets
jekyll-archives:
  enabled:
  - categories
  - tags
  - year
  layouts:
    year: year-archive
    tag: tag-archive
    category: category-archive
